# Light weight Nginx use karenge
FROM nginx:alpine

# Pehle purani default config hata do
RUN rm /etc/nginx/conf.d/default.conf

# Apna updated Nginx config copy karo
# (Compose me dekha tha tumhara config ./frontend/nginx folder me hai)
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Apna static code (HTML/CSS/JS) copy karo
COPY . /usr/share/nginx/html

# Port 80 expose karo
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
