# Light weight Nginx use karenge
FROM nginx:alpine

# Pehle purani default config hata do
RUN rm /etc/nginx/conf.d/default.conf

# Template file copy karo — nginx:alpine ka entrypoint automatically
# envsubst chala ke ${BACKEND_HOST} ko resolve kar dega
# Final output: /etc/nginx/conf.d/default.conf
COPY ./nginx/default.conf.template /etc/nginx/templates/default.conf.template

# Apna static code (HTML/CSS/JS) copy karo
COPY . /usr/share/nginx/html

# Port 80 expose karo
EXPOSE 80

# Default nginx CMD already entrypoint script ko call karta hai
# jo templates process karke nginx start karta hai
CMD ["nginx", "-g", "daemon off;"]
